# _BASE_: "Base-SWINTS_swin.yaml"
# MODEL:
#   WEIGHTS: ".output/mixtrain/model_0079999.pth"
#   SWINTS:
#     NUM_PROPOSALS: 300
#     NUM_CLASSES: 2
#     USE_DICTIONARY: True
#     DICT_PATH: "vn_dictionary.txt"
# DATASETS:
#   TRAIN: ("vintext_train",)
#   TEST:  ("vintext_test",)
# SOLVER:
#   STEPS: (6000,)
#   MAX_ITER: 10000
#   CHECKPOINT_PERIOD: 10000
# INPUT:
#   FORMAT: "RGB"
# TEST:
#   INFERENCE_TH_TEST: 0.5


_BASE_: "Base-SWINTS_swin.yaml"
MODEL:
  WEIGHTS: ".output/mixtrain/model_0079999.pth"
  SWINTS:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 2
    USE_DICTIONARY: True
    DICT_PATH: "vn_dictionary.txt"
  SWINT:
    EMBED_DIM: 96
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    DEPTHS: [2, 2, 6, 2]
    NUM_HEADS: [3, 6, 12, 24]
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.2
    APE: False
    FREEZE_AT: -1
  REC_HEAD:
    BATCH_SIZE: 48
    POOLER_RESOLUTION: [28, 28]
    RESOLUTION: [32, 32]
    LEXICON_THRESHOLD: 0.7
    NUM_CLASSES: 128
DATASETS:
  TRAIN: ("vintext_train",)
  TEST: ("vintext_test",)
SOLVER:
  STEPS: (6000,)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 10000
INPUT:
  FORMAT: "RGB"
TEST:
  INFERENCE_TH_TEST: 0.5